#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/*
 * Central bring-up test selector.
 *
 * Keep only one active test by default. Legacy APP_ENABLE_* macros can still
 * be overridden from compiler definitions, but the check below rejects
 * accidentally enabling more than one test at the same time.
 */
#define APP_TEST_NONE                  0
#define APP_TEST_MOTOR_PWM             1
#define APP_TEST_CHASSIS_OPENLOOP      2
#define APP_TEST_CHASSIS_SPEED_BALANCE 3
#define APP_TEST_WHEEL_SPEED_PI        4
#define APP_TEST_HEADING_HOLD          5
#define APP_TEST_LIDAR_BRINGUP         6

#ifndef APP_ACTIVE_TEST
#define APP_ACTIVE_TEST APP_TEST_LIDAR_BRINGUP
#endif

#if (APP_ACTIVE_TEST < APP_TEST_NONE) || (APP_ACTIVE_TEST > APP_TEST_LIDAR_BRINGUP)
#error "APP_ACTIVE_TEST has an invalid value"
#endif

#ifndef APP_ENABLE_MOTOR_TEST
#define APP_ENABLE_MOTOR_TEST (APP_ACTIVE_TEST == APP_TEST_MOTOR_PWM)
#endif

#ifndef APP_ENABLE_MOTOR_GPIO_STATIC_TEST
#define APP_ENABLE_MOTOR_GPIO_STATIC_TEST 0
#endif

#ifndef APP_ENABLE_CHASSIS_OPENLOOP_TEST
#define APP_ENABLE_CHASSIS_OPENLOOP_TEST (APP_ACTIVE_TEST == APP_TEST_CHASSIS_OPENLOOP)
#endif

#ifndef APP_ENABLE_CHASSIS_DIRECTION_CAL_TEST
#define APP_ENABLE_CHASSIS_DIRECTION_CAL_TEST 0
#endif

#ifndef APP_ENABLE_CHASSIS_GROUND_TRACTION_TEST
#define APP_ENABLE_CHASSIS_GROUND_TRACTION_TEST 0
#endif

#ifndef APP_ENABLE_CHASSIS_SPEED_BALANCE_TEST
#define APP_ENABLE_CHASSIS_SPEED_BALANCE_TEST (APP_ACTIVE_TEST == APP_TEST_CHASSIS_SPEED_BALANCE)
#endif

#ifndef APP_ENABLE_WHEEL_SPEED_PI_TEST
#define APP_ENABLE_WHEEL_SPEED_PI_TEST (APP_ACTIVE_TEST == APP_TEST_WHEEL_SPEED_PI)
#endif

#ifndef APP_ENABLE_HEADING_HOLD_TEST
#define APP_ENABLE_HEADING_HOLD_TEST (APP_ACTIVE_TEST == APP_TEST_HEADING_HOLD)
#endif

#ifndef APP_ENABLE_LIDAR_BRINGUP_TEST
#define APP_ENABLE_LIDAR_BRINGUP_TEST (APP_ACTIVE_TEST == APP_TEST_LIDAR_BRINGUP)
#endif

#define APP_ENABLED_TEST_COUNT \
    (APP_ENABLE_MOTOR_GPIO_STATIC_TEST + \
     APP_ENABLE_MOTOR_TEST + \
     APP_ENABLE_CHASSIS_OPENLOOP_TEST + \
     APP_ENABLE_CHASSIS_DIRECTION_CAL_TEST + \
     APP_ENABLE_CHASSIS_GROUND_TRACTION_TEST + \
     APP_ENABLE_CHASSIS_SPEED_BALANCE_TEST + \
     APP_ENABLE_WHEEL_SPEED_PI_TEST + \
     APP_ENABLE_HEADING_HOLD_TEST + \
     APP_ENABLE_LIDAR_BRINGUP_TEST)

#if APP_ENABLED_TEST_COUNT > 1
#error "Only one APP_ENABLE_* test mode may be enabled at a time"
#endif

#ifndef APP_I2C_SCAN_VERBOSE
#define APP_I2C_SCAN_VERBOSE 0
#endif

#ifndef APP_ENABLE_I2C_BASELINE_DEBUG
#define APP_ENABLE_I2C_BASELINE_DEBUG 1
#endif

#ifndef APP_ENABLE_I2C_BUS_RECOVERY
#define APP_ENABLE_I2C_BUS_RECOVERY 1
#endif

#ifndef APP_LOG_BUFFER_SIZE
#define APP_LOG_BUFFER_SIZE 256
#endif

#ifndef APP_LOG_MUTEX_TIMEOUT_MS
#define APP_LOG_MUTEX_TIMEOUT_MS 100U
#endif

#endif /* APP_CONFIG_H */
